export const hobbies = [
  "Desenhar com lápis",
  "Pintar com aquarela",
  "Pintar com acrílica",
  "Fazer lettering",
  "Praticar caligrafia",
  "Ilustração digital",
  "Design gráfico",
  "Criar logotipos fictícios",
  "Editar fotos",
  "Fotografia urbana",
  "Fotografia da natureza",
  "Fotografia noturna",
  "Escrever poesias",
  "Escrever contos",
  "Escrever um diário",
  "Criar histórias em quadrinhos",
  "Criar roteiros",
  "Storytelling",
  "Criar colagens artísticas",
  "Criar arte abstrata",
  "Aprender violão",
  "Aprender guitarra",
  "Aprender piano",
  "Aprender teclado",
  "Aprender bateria",
  "Aprender ukulele",
  "Produção musical",
  "Criar beats",
  "Ser DJ iniciante",
  "Gravar covers",
  "Treinar canto",
  "Criar playlists temáticas",
  "Editar áudio",
  "Criar podcast",
  "Estudar teoria musical",
  "Improvisar músicas",
  "Aprender baixo",
  "Aprender flauta",
  "Sound design",
  "Mixagem básica",
  "Ler livros",
  "Ler filosofia",
  "Ler ficção científica",
  "Ler biografias",
  "Estudar história",
  "Estudar psicologia",
  "Estudar economia",
  "Estudar astronomia",
  "Resolver enigmas",
  "Resolver sudoku",
  "Resolver palavras-cruzadas",
  "Jogar xadrez",
  "Jogar damas",
  "Aprender lógica",
  "Aprender leitura dinâmica",
  "Estudar estoicismo",
  "Estudar mitologia",
  "Estudar sociologia",
  "Aprender pensamento crítico",
  "Aprender escrita argumentativa",
  "Programar em HTML",
  "Programar em CSS",
  "Programar em JavaScript",
  "Criar sites simples",
  "Criar landing pages",
  "Criar portfólio",
  "Aprender Git e GitHub",
  "Criar automações simples",
  "Criar bots",
  "Estudar UX/UI",
  "Estudar segurança digital",
  "Aprender Linux",
  "Criar scripts",
  "Aprender Python",
  "Criar jogos simples",
  "Modificar jogos",
  "Criar extensões de navegador",
  "Testar softwares",
  "Criar APIs simples",
  "Criar dashboards",
  "Caminhar diariamente",
  "Correr ao ar livre",
  "Treinar em casa",
  "Ir à academia",
  "Praticar yoga",
  "Praticar pilates",
  "Alongamento diário",
  "Calistenia",
  "Pular corda",
  "Meditar",
  "Praticar artes marciais",
  "Treinar boxe",
  "Praticar jiu-jitsu",
  "Praticar capoeira",
  "Dançar",
  "Dança urbana",
  "Dança de salão",
  "Ciclismo",
  "Fazer trilhas",
  "Natação",
  "Meditação guiada",
  "Respiração consciente",
  "Journaling",
  "Praticar gratidão",
  "Minimalismo",
  "Organização pessoal",
  "Planejamento semanal",
  "Criar rotina matinal",
  "Criar rotina noturna",
  "Detox digital",
  "Autoconhecimento",
  "Mindfulness",
  "Controle de hábitos",
  "Leitura espiritual",
  "Estudo religioso",
  "Voluntariado",
  "Estudo de filosofia de vida",
  "Visualização criativa",
  "Autoanálise",
  "Desenvolvimento pessoal",
  "Jogar videogame",
  "Jogos indie",
  "Jogos retrô",
  "Criar jogos de tabuleiro",
  "Jogar RPG",
  "Criar campanhas de RPG",
  "Assistir filmes clássicos",
  "Assistir documentários",
  "Analisar filmes",
  "Analisar séries",
  "Crítica cultural",
  "Criar listas de filmes",
  "Maratonar sagas",
  "Estudar cinema",
  "Criar canal no YouTube",
  "Criar conteúdo no TikTok",
  "Streaming de jogos",
  "Criar memes",
  "Editar vídeos",
  "Criar animações simples"
];